name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    
    services:
      mongodb:
        image: mongo:4.4
        ports:
          - 27017:27017

    env:
      MONGODB_URI: mongodb://localhost:27017
      MONGODB_DATABASE: test_db
      SECRET_KEY: test_secret_key
      JWT_SECRET: test_jwt_secret

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-test.txt
    
    - name: Wait for MongoDB
      run: |
        timeout 30 bash -c 'until nc -z localhost 27017; do sleep 1; done'
        sleep 5
    
    - name: Run tests
      run: |
        python -m pytest tests/ -v
