name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    
    services:
      mongodb:
        image: mongo:4.4
        ports:
          - 27017:27017
        options: >-
          --health-cmd mongo --eval "db.runCommand({ ping: 1 })"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
          --health-start-period 20s

    env:
      MONGODB_URI: mongodb://localhost:27017
      MONGODB_DATABASE: test_db
      SECRET_KEY: test_secret_key
      JWT_SECRET: test_jwt_secret
      PYTHONPATH: ${{ github.workspace }}

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        sudo apt-get update
        sudo apt-get install -y mongodb-clients
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        if [ -f requirements-test.txt ]; then pip install -r requirements-test.txt; fi
        pip install pymongo pytest pytest-cov
    
    - name: Wait for MongoDB
      run: |
        for i in {1..30}; do
          if mongo --eval "db.runCommand({ ping: 1 })" > /dev/null 2>&1; then
            echo "MongoDB is ready!"
            exit 0
          fi
          echo "Waiting for MongoDB... (attempt $i/30)"
          sleep 1
        done
        echo "Error: MongoDB did not become ready in time"
        exit 1
    
    - name: Run tests
      run: |
        python -m pytest tests/ -v --cov=src
